apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-snop
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-snop@sha256:4cc942cc24e77f12c1bc838678d978722929a794f9ec6f5692592f1c40d0f702
        name: my-nodejs
        resources: {}
status: {}
